# High Quality configuration for Nude Generator

# Model settings
model:
  id: "stabilityai/stable-diffusion-2-inpainting"
  device: "auto"
  torch_dtype: "float16"
  cache_dir: null

# Generation parameters (high quality)
generation:
  prompt: "nude body, realistic skin, natural lighting, high quality, detailed anatomy, photorealistic, 8k, masterpiece, professional photography"
  negative_prompt: "clothing, fabric, clothes, shirt, pants, dress, underwear, bra, panties, low quality, blurry, distorted, deformed, ugly, bad anatomy, extra limbs, missing limbs, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, watermark, text, signature, cartoon, anime, 3d render, painting"
  num_inference_steps: 75
  guidance_scale: 8.0
  strength: 1.0
  target_size: [768, 768]

# Processing settings
processing:
  preserve_face: true
  preserve_hands: true
  preserve_background: true
  auto_clothing_detection: true

# Device and memory settings
device:
  enable_memory_efficient_attention: true
  enable_cpu_offload: true
  enable_attention_slicing: true

# Output settings
output:
  format: "PNG"
  quality: 100
  save_mask: true
  save_metadata: true

# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

